# Generated by Django 5.1.7 on 2025-03-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('office', 'Office Supplies'), ('it', 'IT Supplies'), ('consumable', 'Consumables'), ('maint', 'Maintenance'), ('clean', 'Clean Supplies'), ('furniture', 'Furniture'), ('misc', 'Miscellaneous')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('supplier_info', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(choices=[('mfld', 'Marshfield'), ('abb', 'Abbotsford'), ('plo', 'Plover'), ('wr', 'Wisconsin Rapids'), ('wau', 'Wausau'), ('wh', 'Wausau Warehouse'), ('cf', 'Chippewa Falls'), ('cam', 'Cameron'), ('dul', 'Duluth'), ('vir', 'Virginia')], max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
