# Generated by Django 5.1.7 on 2025-05-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_reorder_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_managed',
            field=models.BooleanField(default=False, help_text='Mark as an asset so it can be assigned to User/Department.'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial Number or Asset Tag #', max_length=100, null=True, unique=True),
        ),
    ]
